

# inner/core error message (after standard red "ERROR: "-prefix)
Base.showerror(io::IO, ex::EnduserError) = print(io, ex.msg) 


# this would usually add backtrace after a call to showerror(io,ex); we short-circuit
Base.showerror(io::IO, ex::EnduserError, _bt; backtrace=true) = showerror(io, ex)

